import { Product } from "./types";

export const demoProducts: Product[] = [
  {
    id: "clean-pro-x1",
    slug: "clean-pro-x1",
    name: "CleanPro X1",
    category: "Cleaning Robots",
    short_description: "Autonomous commercial floor scrubbing for malls, hospitals and large facilities.",
    description: "A high-coverage autonomous cleaning platform designed for large indoor facilities. Supports scheduled cleaning, autonomous charging, obstacle avoidance and fleet supervision.",
    industries: ["Malls", "Hospitals", "Airports", "Warehouses"],
    service_modes: ["Purchase", "Rental", "RaaS"],
    image_url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1400&q=85",
    featured: true,
    status: "active",
    runtime: "Up to 6 hours",
    navigation: "LiDAR + vision",
    lead_time: "4–8 weeks"
  },
  {
    id: "serve-bot-s2",
    slug: "serve-bot-s2",
    name: "ServeBot S2",
    category: "Hospitality Robots",
    short_description: "Autonomous food and item delivery for restaurants, cafés and hotels.",
    description: "A compact indoor delivery robot that can move meals, amenities and small items between staff and customers while avoiding people and obstacles.",
    industries: ["Restaurants", "Hotels", "Cafés", "Events"],
    service_modes: ["Purchase", "Rental", "RaaS"],
    image_url: "https://images.unsplash.com/photo-1535378917042-10a22c95931a?auto=format&fit=crop&w=1400&q=85",
    featured: true,
    status: "active",
    payload: "40 kg",
    runtime: "10–12 hours",
    navigation: "SLAM",
    lead_time: "3–6 weeks"
  },
  {
    id: "amr-haul-500",
    slug: "amr-haul-500",
    name: "AMR Haul 500",
    category: "Warehouse AMRs",
    short_description: "Autonomous material transport for warehouses, factories and distribution centers.",
    description: "A flexible autonomous mobile robot for repetitive point-to-point material movement. Suitable for carts, totes and custom top modules.",
    industries: ["Logistics", "Warehouses", "Factories"],
    service_modes: ["Purchase", "Integration", "RaaS"],
    image_url: "https://images.unsplash.com/photo-1565514020179-026b92b84bb6?auto=format&fit=crop&w=1400&q=85",
    featured: true,
    status: "active",
    payload: "500 kg",
    runtime: "8 hours",
    navigation: "LiDAR SLAM",
    lead_time: "6–10 weeks"
  },
  {
    id: "cobot-c12",
    slug: "cobot-c12",
    name: "Cobot C12",
    category: "Collaborative Robots",
    short_description: "Flexible robotic arm for palletizing, machine tending and repetitive production tasks.",
    description: "A collaborative robotic arm platform for industrial automation projects. It can be combined with grippers, vision and safety equipment for application-specific systems.",
    industries: ["Manufacturing", "Packaging", "Metalworking"],
    service_modes: ["Purchase", "Turnkey Integration"],
    image_url: "https://images.unsplash.com/photo-1561144257-e32e8efc6c4f?auto=format&fit=crop&w=1400&q=85",
    featured: true,
    status: "active",
    payload: "12 kg",
    runtime: "Industrial duty",
    navigation: "6-axis arm",
    lead_time: "6–12 weeks"
  },
  {
    id: "quad-inspect-q1",
    slug: "quad-inspect-q1",
    name: "QuadInspect Q1",
    category: "Inspection Robots",
    short_description: "Quadruped inspection platform for industrial, energy and security environments.",
    description: "A mobile quadruped platform that can be equipped with thermal, visual, gas or other sensors for remote inspection tasks in difficult environments.",
    industries: ["Oil & Gas", "Utilities", "Factories", "Security"],
    service_modes: ["Purchase", "Project Integration", "Rental"],
    image_url: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1400&q=85",
    featured: true,
    status: "active",
    runtime: "2–4 hours",
    navigation: "Vision + LiDAR options",
    lead_time: "4–10 weeks"
  },
  {
    id: "solar-clean-s1",
    slug: "solar-clean-s1",
    name: "SolarClean S1",
    category: "Solar Cleaning Robots",
    short_description: "Automated dry-cleaning solution for photovoltaic installations in dusty environments.",
    description: "A modular robotic cleaning system for reducing manual solar-panel cleaning effort and maintaining generation performance in dusty environments.",
    industries: ["Solar Farms", "Industrial Sites", "Commercial Rooftops"],
    service_modes: ["Purchase", "Installation", "Maintenance Contract"],
    image_url: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1400&q=85",
    featured: false,
    status: "active",
    runtime: "Scheduled operation",
    navigation: "Rail / guided options",
    lead_time: "Project dependent"
  },
  {
    id: "reception-r1",
    slug: "reception-r1",
    name: "Reception R1",
    category: "Reception Robots",
    short_description: "Interactive robot for greeting, guidance, promotions and visitor experiences.",
    description: "An interactive reception platform that can present information, guide visitors and support Arabic/English customer journeys at events and public venues.",
    industries: ["Events", "Malls", "Hospitals", "Government", "Showrooms"],
    service_modes: ["Purchase", "Event Rental", "Customization"],
    image_url: "https://images.unsplash.com/photo-1484417894907-623942c8ee29?auto=format&fit=crop&w=1400&q=85",
    featured: false,
    status: "active",
    runtime: "8 hours",
    navigation: "Indoor autonomous",
    lead_time: "4–8 weeks"
  },
  {
    id: "edu-arm-e1",
    slug: "edu-arm-e1",
    name: "EduArm E1",
    category: "Education Robots",
    short_description: "Desktop robotic arm platform for universities, academies and robotics labs.",
    description: "A compact educational robot arm for teaching programming, kinematics, control, vision and AI applications.",
    industries: ["Universities", "Schools", "Training Centers"],
    service_modes: ["Purchase", "Training Package"],
    image_url: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=1400&q=85",
    featured: false,
    status: "active",
    payload: "1–3 kg class",
    runtime: "Lab duty",
    navigation: "4–6 axis arm",
    lead_time: "2–6 weeks"
  }
];

export const categories = [...new Set(demoProducts.map((p) => p.category))];
