"use client";
import { FormEvent, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";

type Row={id:string;name:string;category:string;status:string;featured:boolean};
export function AdminProductManager({products}:{products:Row[]}){
 const router=useRouter(); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const payload=Object.fromEntries(f.entries());const r=await fetch('/api/admin/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();setMsg(r.ok?'Product created.':(d.error||'Could not create product.'));setBusy(false);if(r.ok){e.currentTarget.reset();router.refresh();}}
 async function remove(id:string){if(!confirm('Delete this product?'))return;const r=await fetch(`/api/admin/products/${id}`,{method:'DELETE'});if(r.ok)router.refresh();else setMsg('Could not delete product.');}
 return <div className="admin-products"><div className="admin-panel"><h2>Add product</h2><form className="mini-form" onSubmit={add}><div className="form-grid two"><label>Name<input name="name" required/></label><label>Slug<input name="slug" required placeholder="cleaning-robot-x1"/></label></div><div className="form-grid two"><label>Category<input name="category" required/></label><label>Image URL<input name="image_url" required type="url"/></label></div><label>Short description<textarea name="short_description" required rows={2}/></label><label>Description<textarea name="description" required rows={4}/></label><div className="form-grid two"><label>Industries (comma separated)<input name="industries" placeholder="Hotels, Malls"/></label><label>Models (comma separated)<input name="service_modes" placeholder="Purchase, Rental, RaaS"/></label></div><label className="checkbox"><input name="featured" type="checkbox"/> Featured on home page</label><button className="button" disabled={busy}><Plus size={16}/>{busy?'Saving…':'Add product'}</button>{msg&&<p className="form-message">{msg}</p>}</form></div><div className="admin-panel"><h2>Catalogue</h2><div className="admin-table"><div className="admin-row head"><b>Product</b><b>Category</b><b>Status</b><b></b></div>{products.map(p=><div className="admin-row" key={p.id}><span><b>{p.name}</b>{p.featured&&<small>Featured</small>}</span><span>{p.category}</span><span>{p.status}</span><button aria-label={`Delete ${p.name}`} onClick={()=>remove(p.id)}><Trash2 size={16}/></button></div>)}</div></div></div>
}
